### ISSUE TITLE
RED.comms.publish doesnt effect

### ISSUE THREAD

**Issue by enseitankado** [TotallyInformation/node-red-contrib-jktesting#1]
Is this method  functional in current version of  Node-RED. 
I used it in node.on('input') event and not appears any message at editor.
Can you confirm its availability?

**Comment by TotallyInformation** [comment]
Hi, I can't say that it is totally functional I'm afraid but I think it is. I do get an error in the console when I have it installed but it isn't anything serious. It probably does need a bit of TLC and I don't think that it takes into account Node-RED v1's send/done functions. Still, it should give you some decent ideas about the structure of a custom node.

You could also look at my new [node-red-contrib-gun-db](https://github.com/TotallyInformation/node-red-contrib-gun-db) node as the internals of those are pretty simple. They also follow best practice for both the html and js files. Wrapping the Editor js script in an IIFE for example to ensure that the code stays completely isolated.

**Comment by enseitankado** [comment]
Merhaba, yararlı cevap için teşekkürler. Umarım Node-RED bu yöntemi / düğümü yeni sürümlere dahil eder. O zamana kadar bunu kullanacağım: https://it.knightnet.org.uk/kb/nr-qa/notifying-admin/

Gundb-NR örneği gun-db'yi inceledim. Açıkçası GunJS projesinden siz belirtince haberim oldu var biraz inceleyince oldukça etkilendim. Beni etkileyen kısmı anti merkeziyetçi ve güvenli iletişim alt yapısı oldu. Yine de jktesting'e iyi bir düğüm şablonu olarak başvurmaya devam edeceğim. ;)

**Comment by enseitankado** [comment]
Hello, thanks for the useful answer. I hope Node-RED includes this method / node in new versions. Until then, I will use this: https://it.knightnet.org.uk/kb/nr-qa/notifying-admin/

I examined the Gundb-NR example gun-db. Frankly, I was aware of the GunJS project when you mentioned it. The part that affected me was the anti-centralized and secure communication infrastructure. Still, I will continue to apply to jktesting as a good node template. ;)
